In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [9]:
df = pd.read_csv('CRMLSSold202602.csv', encoding='latin-1')
df.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,CloseDate,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName
0,ContraCosta,BayEast,NaN,NaN,NaN,NaN,NaN,1580000.0,1155696412,2026-02-19,...,NaN,NaN,NaN,NaN,95821,0.0,18682.0,NaN,CRMLS,CRMLS_CCBE
1,OrangeCounty,OrangeCounty,"Carpet,Tile",False,NaN,NaN,False,1100000.0,1155620121,2026-02-27,...,3.0,False,2.0,Irvine Unified,92604,NaN,5000.0,NaN,CRMLS,CRMLS_CRM
2,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,False,NaN,NaN,False,999000.0,1155350576,2026-02-27,...,NaN,False,NaN,NaN,91411,NaN,12005.0,NaN,CRMLS,CRMLS_CL
3,SanDiego,SanDiego,NaN,NaN,NaN,NaN,NaN,1650000.0,1155221012,2026-02-14,...,NaN,NaN,NaN,NaN,91910,0.0,6851.0,NaN,CRMLS,CRMLS_SAND
4,Newport,Newport,NaN,False,NaN,NaN,False,525000.0,1155192177,2026-02-24,...,4.0,False,0.0,ABC Unified,94510,0.0,18730.0,NaN,CRMLS,CRMLS_CRM

In [7]:
df.columns

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'CloseDate', 'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName',
       'Latitude', 'Longitude', 'UnparsedAddress', 'PropertyType',
       'LivingArea', 'ListPrice', 'DaysOnMarket', 'ListOfficeName',
       'BuyerOfficeName', 'CoListOfficeName', 'ListAgentFullName',
       'CoListAgentFirstName', 'CoListAgentLastName', 'BuyerAgentMlsId',
       'BuyerAgentFirstName', 'BuyerAgentLastName', 'FireplacesTotal',
       'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName'],
      dtype='object')

In [8]:
df.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,ElementarySchoolDistrict,BelowGradeFinishedArea,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,1.553000e+03,1.587000e+03,1.587000e+03,1565.000000,1566.000000,1513.000000,1.586000e+03,1587.000000,0.0,0.0,...,0.0,3.0,0.0,1308.000000,1.455000e+03,822.000000,1323.000000,882.000000,1.455000e+03,0.0
mean,1.689354e+06,1.152794e+09,6.961527e+05,34.375855,-118.489168,1764.512227,6.940404e+05,6.759924,NaN,NaN,...,NaN,0.0,NaN,1.355505,2.696471e+04,1.711679,1.658730,177.521474,1.387605e+05,NaN
std,2.306175e+07,5.115470e+05,1.548301e+06,1.439915,1.556437,2612.611198,1.569349e+06,12.376083,NaN,NaN,...,NaN,0.0,NaN,0.478849,8.932801e+04,1.335666,1.045908,597.572564,4.112290e+06,NaN
min,4.250000e+02,1.152119e+09,0.000000e+00,32.570268,-123.809284,0.000000,4.250000e+02,0.000000,NaN,NaN,...,NaN,0.0,NaN,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,NaN
25%,3.500000e+03,1.152402e+09,3.500000e+03,33.679827,-118.465332,1072.000000,3.500000e+03,0.000000,NaN,NaN,...,NaN,0.0,NaN,1.000000,4.996000e+03,1.000000,1.000000,0.000000,5.160500e+03,NaN
50%,6.000000e+03,1.152629e+09,6.400000e+03,34.028254,-118.128678,1478.000000,6.330000e+03,5.000000,NaN,NaN,...,NaN,0.0,NaN,1.000000,7.129000e+03,2.000000,2.000000,0.000000,7.289000e+03,NaN
75%,8.750000e+05,1.153093e+09,9.110000e+05,34.178987,-117.632820,2076.000000,9.087500e+05,10.000000,NaN,NaN,...,NaN,0.0,NaN,2.000000,1.201550e+04,3.000000,2.000000,154.500000,1.304350e+04,NaN
max,5.898880e+08,1.155696e+09,3.160000e+07,40.166515,-115.581547,94619.000000,3.160000e+07,385.000000,NaN,NaN,...,NaN,0.0,NaN,2.000000,1.776812e+06,11.000000,10.000000,9993.000000,1.568160e+08,NaN